const actionTypes = {
  ADD_WAREHOUSE_DATA: "ADD_WAREHOUSE_DATA",
  EDIT_WAREHOUSE_DATA: "EDIT_WAREHOUSE_DATA",
  SET_WAREHOUSE_DATA: "SET_WAREHOUSE_DATA",
  SET_SEARCH_BY_NAME: "SET_SEARCH_BY_NAME",
  SET_BY_FILTER: "SET_BY_FILTER",
};

export default actionTypes;
